SECRET_KEY=''
STOCKFISH='./stockfish_20090216_x64_avx2'
API_KEY=''
LICHESS_CLIENT_ID=''
LICHESS_CLIENT_SECRET=''
LICHESS_AUTHORIZE_URL='https://oauth.lichess.org/oauth/authorize'
LICHESS_TOKEN_URL='https://oauth.lichess.org/oauth'
LICHESS_API_URL='https://lichess.org/api'