version: '3'

networks:
  web:
    external:
      name: web


services:
  magnus:
    image: magnus-server
    build: ./
    volumes:
      - ./:/app/
    networks:
      - web
    labels:
      - traefik.tcp.routers.magnus.service=magnus
      - traefik.tcp.routers.magnus.rule=HostSNI(`magnus.quaternion.media`)
      - traefik.tcp.routers.maguns.tls.passthrough=true
      - traefik.tcp.services.magnus.loadbalancer.server.port=443
