version: '3'

networks:
  web:
    external:
      name: web


services:
  launchchess:
    image: launchchess-server
    build: ./
    volumes:
      - ./:/app/
    networks:
      - web
    labels:
      - traefik.tcp.routers.launchchess.service=launchchess
      - traefik.tcp.routers.launchchess.rule=HostSNI(`launchchess.com`)
      - traefik.tcp.routers.launchchess.tls.passthrough=true
      - traefik.tcp.services.launchchess.loadbalancer.server.port=443
