#!/bin/bash
VERSION=0.1.0
if [ $1 = "version" -o $1 = "v" -o $1 = "-v" ]; then
  echo $VERSION

elif [ $1 = "install" -o $1 = "i" ]; then
  shift
  pip install -r requirements.txt
  docker run -it -v $(pwd)/web:/app -w /app node:current-alpine yarn add "$@"

elif [ $1 = "build" ]; then
  shift
  docker run -it -v $(pwd)/web:/app -w /app -p 5555:5555 node:current-alpine yarn parcel watch --port 5555 --no-cache --dist-dir dist src/index.html

elif [[ $1 = "run" || $1 =~ "serve" ]]; then
  shift
  # uvicorn --reload --host 0.0.0.0 --port 5000 api:app
  uvicorn api:app --port 9999 --ssl-keyfile=./testcert-key.pem --ssl-certfile=./testcert.pem --reload

elif [[ $1 = "prod" || $1 = "production" ]]; then
  shift
  docker-compose down
  docker run -it -v $(pwd)/web:/app -w /app node:current-alpine yarn parcel build --no-cache src/index.html
  # docker run -it --network host -v $(pwd):/app/ magnus-server
  docker-compose up -d "$@"
fi
